export const CURSOS: string[] = [
  'Administração',
  'Agronomia',
  'Análise e Desenvolvimento de Sistemas',
  'Arquitetura e Urbanismo',
  'Artes Visuais',
  'Banco de Dados',
  'Biomedicina',
  'Cibersegurança',
  'Ciência da Computação',
  'Ciência de Dados',
  'Ciências Biológicas',
  'Ciências Contábeis',
  'Ciências Econômicas',
  'Cinema e Audiovisual',
  'Comércio Exterior',
  'Comunicação Social',
  'Criminologia',
  'Defesa Cibernética',
  'Design de Interiores',
  'Design de Moda',
  'Design de Produto',
  'Design Gráfico',
  'Direito',
  'Educação Física',
  'Enfermagem',
  'Engenharia Aeroespacial',
  'Engenharia Ambiental',
  'Engenharia Biomédica',
  'Engenharia Civil',
  'Engenharia de Computação',
  'Engenharia de Controle e Automação',
  'Engenharia de Produção',
  'Engenharia de Software',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Mechatrônica',
  'Engenharia Química',
  'Estética e Cosmética',
  'Eventos',
  'Farmácia',
  'Filosofia',
  'Fisioterapia',
  'Fonoaudiologia',
  'Fotografia',
  'Gastronomia',
  'Geografia',
  'Gestão Ambiental',
  'Gestão Comercial',
  'Gestão da Tecnologia da Informação',
  'Gestão de Recursos Humanos',
  'Gestão de Segurança Privada',
  'Gestão de Turismo',
  'Gestão Financeira',
  'Gestão Hospitalar',
  'Gestão Pública',
  'História',
  'Hotelaria',
  'Investigação e Perícia Criminal',
  'Jogos Digitais',
  'Jornalismo',
  'Letras (Português/Inglês/Espanhol)',
  'Logística',
  'Marketing',
  'Marketing Digital',
  'Matemática',
  'Medicina',
  'Medicina Veterinária',
  'Moda',
  'Museologia',
  'Música',
  'Nutrição',
  'Odontologia',
  'Pedagogia',
  'Processos Gerenciais',
  'Produção Cultural',
  'Psicologia',
  'Psicopedagogia',
  'Publicidade e Propaganda',
  'Radiologia',
  'Relações Internacionais',
  'Relações Públicas',
  'Redes de Computadores',
  'Saneamento Ambiental',
  'Secretariado Executivo',
  'Serviço Social',
  'Serviços Jurídicos e Notariais',
  'Sistemas de Informação',
  'Sistemas para Internet',
  'Teatro',
  'Teologia',
  'Terapia Ocupacional',
  'Turismo',
]
